# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: Build
on: [push, pull_request]

jobs:
  init:
    name: init
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
      skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
      yarn-cache-dir: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      checksum: ${{ steps.checksum.outputs.checksum }}
    steps:
      - uses: actions/checkout@v3

      - id: ci-skip-step
        uses: mstachniuk/ci-skip@v1

      - name: Get yarn cache dir
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Get src checksum
        id: checksum
        run: echo "::set-output name=checksum::${{ hashFiles('packages/*/src/**/*') }}-${{ hashFiles('packages/*/package.json') }}"

  build:
    name: build
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download artifact
        uses: qiwi-forks/action-download-artifact@v0.2.1
        with:
          name: artifact-${{ needs.init.outputs.checksum }}
          workflow: 'ci.yaml'
          workflow_conclusion: false
          nothrow: true
          search_artifacts: true

      - name: Check artifact
        if: always()
        id: check-artifact
        run: echo "::set-output name=exists::$([ -e "artifact.tar" ] && echo true || echo false)"

      - uses: actions/cache@v3
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        id: yarn-cache
        with:
          path: ${{ needs.init.outputs.yarn-cache-dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        run: yarn

      - name: Build
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        run: |
          yarn build
          tar -cvf artifact.tar packages/*/lib packages/*/styleguide package.json

      - name: Save target (artifact)
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ needs.init.outputs.checksum }}
          retention-days: ${{ github.ref == 'refs/heads/master' && '30' ||  '7' }}
          path: artifact.tar
