# https://github.com/actions/upload-artifact/issues/181
# https://github.community/t/job-output-cannot-be-using-when-triggering-workflow-from-job/250825/4
# https://github.com/afonsoc12/docker-cloudflared/blob/06ee46a846e204fe5c0fd6a6fa3954b6120a3119/.github/workflows/docker_build_master.yml

name: Build
on:
  workflow_dispatch:
    inputs:
      yarn-cache-dir:
        description: The directory where the yarn cache is stored.
        required: true
        type: string
      checksum:
        description: The checksum of the src dir + yarn.lock
        required: true
        type: string

  workflow_call:
    inputs:
      yarn-cache-dir:
        description: The directory where the yarn cache is stored.
        required: true
        type: string
      checksum:
        description: The checksum of the src dir + yarn.lock
        required: true
        type: string

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download artifact
        uses: qiwi-forks/action-download-artifact@v0.2.1
        with:
          name: artifact-${{ github.event.inputs.checksum }}
          workflow: 'ci.yaml'
          workflow_conclusion: false
          nothrow: true
          search_artifacts: true

      - name: Check artifact
        if: always()
        id: check-artifact
        run: echo "::set-output name=exists::$([ -e "artifact.tar" ] && echo true || echo false)"

      - uses: actions/cache@v3
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        id: yarn-cache
        with:
          path: ${{ github.event.inputs.yarn-cache-dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        run: yarn

      - name: Build
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        run: |
          yarn build
          tar -cvf artifact.tar packages/*/lib packages/*/styleguide package.json

      - name: Save target (artifact)
        if: ${{ steps.check-artifact.outputs.exists == 'false' }}
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ needs.init.outputs.checksum }}
          retention-days: ${{ github.ref == 'refs/heads/master' && '30' ||  '7' }}
          path: artifact.tar
